### PR TITLE
Avoid loosing ehcache stats when 1 tier and also fix library loading 

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
Hi guys, I am merging fast this one... See PR in other project about `.add(new StoreStatisticsConfiguration(true))` and see with @henri-tremblay and https://github.com/ehcache/ehcache3/pull/2433

**Comment by henri-tremblay** [comment]
Can I ask why the tier statistics are useful to you in this case?

**Comment by anthonydahanne** [comment]
not sure I understood the need for ```serviceConfiguration.add(new StoreStatisticsConfiguration(true));```

**Comment by mathieucarbou** [comment]
@henri-tremblay : Tiny Pounder is the tool used to test. When management is activated, we have to generate stats from ehcache clients up to the cluster.

**Comment by mathieucarbou** [comment]
@anthonydahanne you have to talk to @henri-tremblay and @chrisdennis for the meaning of `.add(new StoreStatisticsConfiguration(true));` on a cache config. For now with the new Ehcache code in master, this is what we need to get ALL the statistics flowing and not just parts of them.

**Comment by henri-tremblay** [comment]
The hypothesis is that normal human being does not need cache + tier stats when having only one tier. Which is why I was curious about your use-case.

**Pull request merged**
